### ISSUE TITLE
Exception - toArray method when enum inside

### ISSUE THREAD

**Issue by DaveBugg** [forrest79/PhPgSql#41]
Hey,

After a long time working with MySQL, I've recently started using pgsql and opted for your library. When attempting to retrieve a user row from the table, everything went smoothly:
```php
$a = PGDB::$CONNECT->query('SELECT id, login, access FROM users WHERE token=? LIMIT 1', $token)->fetch();
```
However, when trying to obtain an array, I encountered an error:
```php
$a = $a->toArray();   // Error: Can't parse type 'users_access' for value 'admin'.
```
The data type users_access is an enum type, so if I write ('SELECT id, login, access::text .... ), everything works fine. 
I'm not entirely sure if this is an error, but I thought I'd mention it just in case.

**Comment by forrest79** [comment]
Hi, nice to hear that there is a new Postge user :-)

This library is trying to convert all Postgres types to PHP - there is a default data type parser `src/Db/DataTypeParsers/Basic.php` and this type parser doesn't know the `users_access` data type. You can extend this data type parser and add this type or if you're OK with parsing this type as a string, casting it as a `::text` is also possible.
